version: '3'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-3333}:${PORT_WEB_UI-3333}"
    environment:
      - SERVICES=${SERVICES-s3,sqs,dynamodb}
      - DEBUG=${DEBUG-1}
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
      - PORT_WEB_UI=${PORT_WEB_UI-3333}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  simple-node-service:
    image: local/simple-node-service:latest
    build:
      context: ./../simple-node-service
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    ports:
      - 7777:8080
    environment:
      - NODE_PORT=8080
      - NODE_QUEUE_HOST=http://localstack:4566
      - NODE_QUEUE_URL=http://localstack:4566/000000000000/SimpleQueue
      - NODE_ACCESS_KEY_ID=na
      - NODE_SECRET_ACCESS_KEY=na
      - NODE_REGION=region
      - NODE_LOGGER=dev
    depends_on:
      - localstack
    restart: always

  simple-python-service:
    image: local/simple-python-service:latest
    build:
      context: ./../simple-python-service
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    environment:
      - PY_HOST=localstack
      - PY_INTERVAL=5
      - PY_QUEUE_NAME=SimpleQueue
      - PY_BUCKET_NAME=simplecdkstack-simplebucket
      - PY_DEV=true
    depends_on:
      - simple-node-service
      - localstack
    restart: always